name: Deploy Supabase Functions

on:
  workflow_dispatch:
    inputs:
      project_ref:
        description: 'Supabase Project Ref (e.g., raiccyhtjhsgmouzulhn)'
        required: true
      allowed_origin:
        description: 'Comma-separated allowed origins (e.g., http://localhost:5173)'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Supabase CLI
        run: |
          npm i -g supabase@^2

      - name: Supabase Login
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          if [ -z "$SUPABASE_ACCESS_TOKEN" ]; then echo 'Missing SUPABASE_ACCESS_TOKEN secret' && exit 1; fi
          supabase login --token "$SUPABASE_ACCESS_TOKEN"

      - name: Set Function Secrets
        env:
          PROJECT_REF: ${{ github.event.inputs.project_ref }}
          ALLOWED_ORIGIN: ${{ github.event.inputs.allowed_origin }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          if [ -z "$GEMINI_API_KEY" ]; then echo 'Missing GEMINI_API_KEY secret' && exit 1; fi
          supabase functions secrets set --project-ref "$PROJECT_REF" \
            ALLOWED_ORIGIN="$ALLOWED_ORIGIN" \
            GEMINI_API_KEY="$GEMINI_API_KEY"

      - name: Deploy Edge Functions
        env:
          PROJECT_REF: ${{ github.event.inputs.project_ref }}
        run: |
          for function_dir in supabase/functions/*; do
            if [ -d "$function_dir" ]; then
              function_name=$(basename "$function_dir")
              if [[ "$function_name" != "_shared" && "$function_name" != ".*" ]]; then
                echo "Deploying function: $function_name"
                supabase functions deploy "$function_name" --project-ref "$PROJECT_REF" --no-verify-jwt
              fi
            fi
          done

      - name: Health Check suggest-subtasks
        env:
          PROJECT_REF: ${{ github.event.inputs.project_ref }}
        run: |
          curl -sSf "https://${PROJECT_REF}.supabase.co/functions/v1/suggest-subtasks?health=1" -H 'Origin: http://localhost:5173' -i | sed -n '1,15p'